POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "bob",
    "number": "58430958"
}

# DELETE http://localhost:3001/api/persons/2
# GET http://localhost:3001/api/persons